name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: AsafMah/openai-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_comment_lgtm: false
          openai_heavy_model: gpt-4
          openai_base_url: ${{ secrets.OPENAI_URL }}
          path_filters: |
            !dist/**
            !**/*.pb.go
            !**/*.lock
            !**/*.yaml
            !**/*.yml
            !**/*.cfg
            !**/*.toml
            !**/*.ini
            !**/*.mod
            !**/*.sum
            !**/*.work
            !**/*.json
            !**/*.mmd
            !**/*.svg
            !**/*.png
            !**/*.dot
            !**/*.md5sum
            !**/*.wasm
            !**/gen/**
            !**/_gen/**
            !**/generated/**
            !**/vendor/**
            !**/ai.yml
