# This workflow will install the dependencies, run tests and lint every push

name: Build Java

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    strategy:
      matrix:
        java: ['11','17','21']
    name: Java ${{ matrix.java }}
    steps:
      - name: Azure login
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
          client-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Run formatter
        run: mvn formatter:validate
        continue-on-error: true
      - name: Run the Maven verify phase
        run: mvn verify
        env:
          DM_CONNECTION_STRING: ${{ secrets.DM_CONNECTION_STRING }}
          ENGINE_CONNECTION_STRING: ${{ secrets.ENGINE_CONNECTION_STRING }}
          TEST_DATABASE: ${{ secrets.TEST_DATABASE }}
          APP_ID: ${{ secrets.APP_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CI_EXECUTION: 1
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          files: |
            data/target/surefire-reports/*.xml
            ingest/target/surefire-reports/*.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
